package com.payments.tbjava.domain;

/**
 * Per-transfer result code. Mirrors TigerBeetle's CreateTransferResult values
 * so clients written against TB protocol can switch with minimal changes.
 */
public enum CreateTransferResult {
    OK,
    EXISTS,
    EXISTS_WITH_DIFFERENT_FIELDS,
    LINKED_EVENT_FAILED,

    // Field validation
    ID_MUST_NOT_BE_ZERO,
    DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO,
    CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO,
    ACCOUNTS_MUST_BE_DIFFERENT,
    AMOUNT_MUST_NOT_BE_ZERO,
    LEDGER_MUST_NOT_BE_ZERO,
    CODE_MUST_NOT_BE_ZERO,
    FLAGS_ARE_MUTUALLY_EXCLUSIVE,

    // Reference checks
    DEBIT_ACCOUNT_NOT_FOUND,
    CREDIT_ACCOUNT_NOT_FOUND,
    ACCOUNTS_MUST_HAVE_SAME_LEDGER,
    TRANSFER_MUST_HAVE_SAME_LEDGER_AS_ACCOUNTS,

    // Account state
    DEBIT_ACCOUNT_CLOSED,
    CREDIT_ACCOUNT_CLOSED,

    // Balance constraints
    EXCEEDS_DEBITS_LIMIT,
    EXCEEDS_CREDITS_LIMIT,
    OVERFLOWS_DEBITS_PENDING,
    OVERFLOWS_DEBITS_POSTED,
    OVERFLOWS_CREDITS_PENDING,
    OVERFLOWS_CREDITS_POSTED,

    // Pending / two-phase
    PENDING_TRANSFER_NOT_FOUND,
    PENDING_TRANSFER_NOT_PENDING,
    PENDING_TRANSFER_EXPIRED,
    PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID,
    PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID,
    PENDING_TRANSFER_HAS_DIFFERENT_LEDGER,
    PENDING_TRANSFER_HAS_DIFFERENT_AMOUNT,
    EXCEEDS_PENDING_TRANSFER_AMOUNT,
}
